name: CI - Automation Test runner

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Java 17 and Maven Environment
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Standard Tests
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: mvn clean test

      - name: Publish JUnit Test Results to PR Page
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "**/target/surefire-reports/*.xml"